### ISSUE TITLE
Allow using this action with SSH delpoy key instead of Personal Access Token

### ISSUE THREAD

**Issue by pksunkara** [shalzz/zola-deploy-action#16]
This is possible because you can see it being used [here](https://github.com/JamesIves/github-pages-deploy-action/tree/dev#using-an-ssh-deploy-key-)

I personally would just checkout the repo with `ssh-key` instead of running an agent step. But both cases can be supported with just pushing to the remote directly with token absent.

**Comment by tp** [comment]
You're right, looks like a simpler setup is possible.

I didn't go into the details yet, but just bundled this action with another "publish to GitHub Pages" one, and indeed it works without any complicated token setup:

```
name: Build and deploy

on:
  push:
    branches: [master]

jobs:
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: shalzz/zola-deploy-action
        uses: shalzz/zola-deploy-action@d74c86d3222b4aaf555f33ce7e17b8839628e0d5
        env:
          PAGES_BRANCH: gh-pages
          BUILD_DIR: .
          BUILD_ONLY: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@b8f8d291c97fe0edd9fb4ee73018163593418e8f
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by pksunkara** [comment]
Agree, `BUILD_ONLY` works.

```yml
name: Deploy
on:
  push:
    branches: [master]
jobs:
  docs:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: shalzz/zola-deploy-action@master
        env:
          BUILD_ONLY: true
      - name: Deploy
        if: ${{ success() }}
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: public
```
