### ISSUE TITLE
Build breaks with co-located assets

### ISSUE THREAD

**Issue by pfesenmeier** [shalzz/zola-deploy-action#28]
Hello, I have a Zola shortcode
`templates/shortcodes/resize_image.html`

And a post using it to render several co-located photos:
```
content/hack-a-thon-2021/
                     - index.html
                     - photo1.jpeg
                     - photo2.jpeg
```
Build and serve works fine locally. However, during the GHA, it fails with this error:

```
 Error: Failed to render content of /github/workspace/content/hack-a-thon-2021/index.md
Reason: Failed to render resize_image shortcode
Reason: Failed to render 'shortcodes/resize_image.html'
Reason: Function call 'resize_image' failed
Reason: `resize_image`: Cannot find path: content/hack-a-thon-2021/rpi-overhead.jpeg
```
my action is copy-pasted from zola site:
```
# On every push this script is executed
on: push
name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.13.0
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          # Provide personal access token
          TOKEN: ${{ secrets.TOKEN }}
```
