### ISSUE TITLE
Example script in the readme fails while running

### ISSUE THREAD

**Issue by BillyDM** [shalzz/zola-deploy-action#36]
The example script given in the README fails while running.

It fails with the error `/entrypoint.sh: line 63: cd: docs: No such file or directory`.

When I remove the line `BUILD_DIR: docs` from the script, it runs successfully.

The script for reference:
```yml
on: push
name: Build and deploy on push
jobs:
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: shalzz/zola-deploy-action
      uses: shalzz/zola-deploy-action@master
      env:
        PAGES_BRANCH: gh-pages
        BUILD_DIR: docs
        BUILD_FLAGS: --drafts
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
