### ISSUE TITLE
    BUILD_THEMES: false as no effect

### ISSUE THREAD

**Issue by gagarine** [shalzz/zola-deploy-action#41]
adding   `BUILD_THEMES: false` seems to have no effect has no effect and because their is no gitmodules it fail:
```
Fetching themes
fatal: No url found for submodule path 'themes/tale-zola' in .gitmodules
```

My config:
```
on:
  push:
    branches:
      - main
name: Build and deploy on push
jobs:
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: shalzz/zola-deploy-action
      uses: shalzz/zola-deploy-action@master
      env:
        PAGES_BRANCH: gh-pages
        TOKEN: ${{ secrets.TOKEN }}
        BUILD_THEMES: false
```

I checked the source code of this action, and don't understand what it doesn't works.
