### ISSUE TITLE
Custom Syntah Highlighthing theme not working

### ISSUE THREAD

**Issue by videbar** [shalzz/zola-deploy-action#44]
I [opened an issue about this a few months](https://github.com/shalzz/zola-deploy-action/issues/33) ago which I closed because I was using an outdated version of zola.

I am using [a custom highlighting theme](https://www.getzola.org/documentation/content/syntax-highlighting/#custom-highlighting-themes) called `darker-nord`. The way I have set it up is the following.

I have this in my `config.toml` file:

```toml
[markdown]
# Code highlighting
highlight_code = true
# Custom theme
extra_syntaxes_and_themes = ["extra-highlight-themes"]
highlight_theme = "darker-nord"
```

and the following file structure:

```
.
├── config.toml
└── extra-highlight-themes
    └── darker-nord.tmTheme
```
This works fine when running it locally, but the github action fails to build the site:

```
Error: Highlight theme darker-nord defined in config does not exist.
```
