### ISSUE TITLE
deployment fails with "error: wrong number of arguments, should be 2"

### ISSUE THREAD

**Issue by flxzt** [shalzz/zola-deploy-action#71]
see: 

https://github.com/flxzt/mercury/actions/runs/4523922956/jobs/7967401062

I am using the example shown in the readme:

```yaml
name: Zola on GitHub Pages

on: 
 push:
  branches:
   - main

jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v3.0.0
    - name: Build and deploy
      uses: shalzz/zola-deploy-action@v0.17.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by shalzz** [comment]
The latest commit branch should resolve this. Try using `uses: shalzz/zola-deploy-action@master` in your workflow file.

Also if you're building a site without a theme submodule, disable pulling in the submodule with the `BUILD_THEMES` mentioned here: https://github.com/shalzz/zola-deploy-action#environment-variables

**Comment by flxzt** [comment]
that fixed it. thanks!

**Comment by muzimuzhi** [comment]
The `actions/checkout` action learnt a new input [`set-safe-directory: <path>`](https://github.com/actions/checkout#usage) since v3 (see https://github.com/actions/checkout/commit/0ffe6f9c5599e73776da5b7f113e994bc0a76ede), so I think sth like
```yaml
      - uses: actions/checkout@v3
        with:
          set-safe-directory: '*'
```
should work as well.
