### ISSUE TITLE
fatal: Authentication failed 

### ISSUE THREAD

**Issue by amrirasyidi** [shalzz/zola-deploy-action#77]
I got this error while trying to publish my github pages.
`fatal: Authentication failed for 'https://github.com/amrirasyidi/pmed.git/'`

I followed the instruction from [here](https://www.getzola.org/documentation/deployment/github-pages/) and use the script in this repo as the yaml file as such:

```
name: Zola on GitHub Pages

on: 
 push:
  branches:
   - master

jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@v3.0.0
    - name: Build and deploy
      uses: shalzz/zola-deploy-action@v0.17.2
      env:
        GITHUB_TOKEN:
```

I provided the GITHUB_TOKEN ofc.

What can I do to fix this error?
